name: Jupyter Notebook Static Analysis with nbQA

on:
  push:
    paths:
      - '**.ipynb'
  workflow_dispatch:

jobs:
  nbqa_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbQA flake8

      - name: Run nbQA with flake8
        id: nbqa_report
        run: |
          find . -type f -name "*.ipynb" -exec nbqa flake8 {} \;

      - name: Create issue with nbQA report
        uses: repo-sync/github-tag-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: nbqa-report
          tag_body_file: ./nbqa-report.txt

      - name: Get Pull Request Number
        id: pr_number
        run: echo "::set-output name=pr_number::$(jq --raw-output '.pull_request.number' $GITHUB_EVENT_PATH)"

      - name: Add comment to pull request
        uses: actions/github-script@v4
        if: steps.pr_number.outputs.pr_number != 'null'
        with:
          script: |
            github.issues.createComment({
              issue_number: ${{ steps.pr_number.outputs.pr_number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'The static analysis report with nbQA has been generated. Please review it and make the necessary changes.'
            })
