name: Jupyter Notebook Static Analysis with nbQA

on:
  pull_request:
    paths:
      - '**.ipynb'
  workflow_dispatch:

jobs:
  nbqa_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbQA flake8

      - name: Run nbQA with flake8
        run: |
          find . -type f -name "*.ipynb" -exec nbqa flake8 {} \; 2>&1 | tee nbqa-report.txt

      - name: Check if nbQA report is empty
        id: check_report
        run: |
          if [[ -s nbqa-report.txt ]]; then
            echo "::set-output name=has_report::true"
          else
            echo "::set-output name=has_report::false"
          fi

      - name: Add comment to pull request with nbQA report
        if: steps.check_report.outputs.has_report == 'true' && github.event_name == 'pull_request'
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('./nbqa-report.txt', 'utf8');
            const pr_number = context.payload.pull_request.number;
            await github.issues.createComment({
              issue_number: pr_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `The static analysis report with nbQA has been generated. Please review it and make the necessary changes:\n\`\`\`\n${report}\n\`\`\``
            });
